openapi: 3.1.0
info:
  title: POI API
  description: |
    REST API for Points of Interest (POI) data.

    Provides endpoints for retrieving nearby attractions, beaches, golf courses,
    and other points of interest to display on the location map (FR-025, FR-026).

    This is an extension to the main Booking API for the booking frontend feature.
  version: 1.0.0

servers:
  - url: https://api.booking.example/v1
    description: Production server
  - url: https://api-dev.booking.example/v1
    description: Development server
  - url: http://localhost:3001/api
    description: Local development

tags:
  - name: POI
    description: Points of Interest for location map

paths:
  /pois:
    get:
      tags:
        - POI
      summary: List all points of interest
      description: |
        Returns all active POIs for display on the location map.

        POIs include nearby beaches, golf courses, restaurants, attractions,
        shopping centers, and transport hubs. Each POI has coordinates for
        map markers and details for popup display.

        **Filtering:**
        - Use `category` to filter by POI type
        - Results are sorted by `display_order` within each category
        - Only active POIs (`is_active: true`) are returned
      operationId: listPOIs
      parameters:
        - name: category
          in: query
          description: Filter POIs by category
          required: false
          schema:
            $ref: '#/components/schemas/POICategory'
      responses:
        '200':
          description: List of POIs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/POIListResponse'
              examples:
                all_pois:
                  summary: All POIs
                  value:
                    pois:
                      - poi_id: "beach-guardamar"
                        category: "beach"
                        name: "Guardamar Beach"
                        description: "Long sandy beach with pine-backed dunes and Blue Flag status."
                        latitude: 38.0873
                        longitude: -0.6556
                        distance_km: 15
                        distance_text: "20 min drive"
                        icon: "beach"
                        url: "https://goo.gl/maps/guardamar"
                        is_active: true
                        display_order: 1
                        created_at: "2026-01-01T00:00:00Z"
                        updated_at: "2026-01-01T00:00:00Z"
                      - poi_id: "golf-la-marquesa"
                        category: "golf"
                        name: "La Marquesa Golf"
                        description: "18-hole course with stunning views and well-maintained greens."
                        latitude: 38.0523
                        longitude: -0.7834
                        distance_km: 3
                        distance_text: "5 min drive"
                        icon: "golf"
                        url: "https://lamarquesagolf.com"
                        is_active: true
                        display_order: 1
                        created_at: "2026-01-01T00:00:00Z"
                        updated_at: "2026-01-01T00:00:00Z"
                    total: 2
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalError'

  /pois/{poi_id}:
    get:
      tags:
        - POI
      summary: Get a single POI by ID
      description: Returns detailed information about a specific POI.
      operationId: getPOI
      parameters:
        - name: poi_id
          in: path
          description: Unique POI identifier
          required: true
          schema:
            type: string
          example: "beach-guardamar"
      responses:
        '200':
          description: POI details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/POI'
        '404':
          description: POI not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          $ref: '#/components/responses/InternalError'

components:
  schemas:
    POICategory:
      type: string
      description: Category of point of interest
      enum:
        - beach
        - golf
        - restaurant
        - attraction
        - shopping
        - transport
      example: "beach"

    POI:
      type: object
      description: Point of Interest for the location map
      required:
        - poi_id
        - category
        - name
        - description
        - latitude
        - longitude
        - distance_km
        - is_active
        - display_order
        - created_at
        - updated_at
      properties:
        poi_id:
          type: string
          description: Unique POI identifier (UUID or slug)
          example: "beach-guardamar"
        category:
          $ref: '#/components/schemas/POICategory'
        name:
          type: string
          description: Display name
          example: "Guardamar Beach"
        description:
          type: string
          description: Brief description (1-2 sentences)
          example: "Long sandy beach with pine-backed dunes and Blue Flag status."
        latitude:
          type: number
          format: double
          description: GPS latitude coordinate
          minimum: -90
          maximum: 90
          example: 38.0873
        longitude:
          type: number
          format: double
          description: GPS longitude coordinate
          minimum: -180
          maximum: 180
          example: -0.6556
        distance_km:
          type: number
          format: double
          description: Distance from property in kilometers
          minimum: 0
          example: 15
        distance_text:
          type: string
          description: Human-readable distance (e.g., "15 min drive")
          nullable: true
          example: "20 min drive"
        icon:
          type: string
          description: Optional icon identifier for map marker
          nullable: true
          example: "beach"
        url:
          type: string
          format: uri
          description: Optional external link (website, Google Maps)
          nullable: true
          example: "https://goo.gl/maps/guardamar"
        is_active:
          type: boolean
          description: Whether to display on map
          example: true
        display_order:
          type: integer
          description: Sort order within category
          example: 1
        created_at:
          type: string
          format: date-time
          description: ISO 8601 creation timestamp
          example: "2026-01-01T00:00:00Z"
        updated_at:
          type: string
          format: date-time
          description: ISO 8601 last update timestamp
          example: "2026-01-01T00:00:00Z"

    POIListResponse:
      type: object
      description: API response for POI list
      required:
        - pois
        - total
      properties:
        pois:
          type: array
          description: List of POIs
          items:
            $ref: '#/components/schemas/POI'
        total:
          type: integer
          description: Total number of POIs returned
          example: 6

    Error:
      type: object
      description: Standard error response
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: Error code
          example: "POI_NOT_FOUND"
        message:
          type: string
          description: Human-readable error message
          example: "POI with ID 'invalid-id' not found"
        details:
          type: object
          description: Additional error context
          additionalProperties: true

  responses:
    BadRequest:
      description: Invalid request parameters
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: "INVALID_CATEGORY"
            message: "Invalid category 'invalid'. Must be one of: beach, golf, restaurant, attraction, shopping, transport"

    InternalError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: "INTERNAL_ERROR"
            message: "An unexpected error occurred"
